name: Frontend Base Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'base-check'
  cancel-in-progress: true

jobs:
  base-check:
    name: Lint, Format & Build Checks
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install & Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Clean Install
        run: npm ci

      - name: Run Lint & Prettier checks
        run: npm run lint:ci

      - name: Run Build
        run: npm run build